# Generated by Django 3.1.1 on 2020-10-19 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic', '0002_emailtemp_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemp',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
