# Generated by Django 3.1.1 on 2020-11-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic', '0003_auto_20201018_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemp',
            name='sender',
            field=models.CharField(default='', max_length=200),
        ),
    ]
